server.port: 8078
spring:
  application.name: GATEWAY
  cloud:
    gateway.routes:
      - id: service-1
        uri: lb://SERVICE-1
        predicates:
          - Path=/service1/**
    discovery.enabled: true
eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl.defaultZone: http://localhost:8079/eureka