server.port: 8078
spring:
  application.name: GATEWAY
  cloud:
    gateway.routes:
      - id: service-1
        uri: lb://SERVICE-1
        predicates:
          - Path=/service1/**
        filters:
          - name: CircuitBreaker
            args:
              name: service1CircuitBreaker
              fallbackUri: forward:/fallback/service1
      - id: service-2
        uri: lb://SERVICE-2
        predicates:
          - Path=/service2/**
        filters:
          - name: CircuitBreaker
            args:
              name: service1CircuitBreaker
              fallbackUri: forward:/fallback/service2
    discovery.enabled: true
eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl.defaultZone: http://localhost:8079/eureka